feat: [C4R-198] restrict NGO
code4romania/onghub pull request #100
Opened 2022-09-27 14:24 UTC by OlteanuCosmin

- C4R-654
- closes C4R-657 and C4R-385.

2022-09-28 09:08 UTC, radulescuandrew requested changes

2022-09-28 09:08 UTC, radulescuandrew commented on frontend/src/services/request/Request.service.ts
> +export const restrictOrganizationRequest = (organizationId: number): Promise<any> => {
Move to organization

2022-09-28 09:22 UTC, OlteanuCosmin commented on backend/src/modules/organization/services/organization.service.ts
>        throw new BadRequestException(ORGANIZATION_ERRORS.RESTRICT);
Redenumit in `ORGANIZATION_ERRORS.ALREADY_RESTRICTED`.

2022-09-28 09:23 UTC, OlteanuCosmin commented on backend/src/modules/organization/services/organization.service.ts
> +        'users',
Am adaugat o functie noua care ia organizatia doar cu utilizatorii.

2022-09-28 09:25 UTC, OlteanuCosmin commented on backend/src/modules/organization/services/organization.service.ts
> +    this.mailService.sendEmail({
Repozitionat dupa actualizarea in baza de date.

2022-09-28 09:31 UTC, OlteanuCosmin commented on frontend/src/pages/organization/OrganizationProfile.tsx
> +      {role !== UserRole.EMPLOYEE && (
SuperAdmin-ul nu apeleaza organization-profile, deci nu are cum sa vada butonul.

2022-09-28 09:39 UTC, OlteanuCosmin commented on frontend/src/services/request/Request.service.ts
> +export const restrictOrganizationRequest = (organizationId: number): Promise<any> => {
Mutat si actualizat.

2022-09-28 09:39 UTC, OlteanuCosmin commented on backend/src/modules/organization/controllers/organization-profile.controller.ts
> +  @Post('request/:id/restrict')
Redenumit.

2022-09-28 11:27 UTC, OlteanuCosmin commented on frontend/src/pages/organization/OrganizationProfile.tsx
> +          refetch();
Nu este folosit ca sa se faca refresh automat dupa actiune?

2022-10-03 08:11 UTC, OlteanuCosmin commented on frontend/src/index.css
> +.button_restrict_org {
Done.

2022-10-03 09:07 UTC, birloiflorian requested changes

2022-10-03 09:07 UTC, birloiflorian commented on frontend/src/AuthProvider.tsx
> +    isOrganizationRestricted: false,
Poate in loc sa avem un al doilea flag de restricted sa avem un restrictedReason care are fi key-ul din translations al mesajului pe care il afisam utilizatorului.

2022-10-03 09:07 UTC, birloiflorian commented on frontend/src/AuthProvider.tsx
> +            useErrorToast('User not found');
Missing translation.

2022-10-03 09:07 UTC, birloiflorian commented on frontend/src/common/guards/AuthGuards.tsx
> +  if (auth.isOrganizationRestricted) {
Ar trebui sa fie o singura ruta pentru restricted

2022-10-03 09:07 UTC, birloiflorian commented on frontend/src/pages/restricted-organization/RestrictedOrganization.tsx
> +import React from 'react';
Pagina asta nu ar trebui sa existe ci doar sa schimbam mesajul din pagina de restricted cu cel salvat in context ca RestrcitedReason

2022-10-04 07:20 UTC, radulescuandrew commented
Do we ever close this PR?

2022-10-04 13:37 UTC, radulescuandrew commented on backend/src/mail/templates/restrict-organization-admin.hbs
> +    trimite un mail catre contact@onghub.ro.
@birloiflorian Da, am lasat comment in PR-ul cu mail deschis de Andreea sa facem variabile pentru fiecare mail in parte.

2022-10-04 13:44 UTC, radulescuandrew approved these changes

2022-10-04 13:45 UTC, merged