fix: [C4R-694] & [C4R-695] fixed small bugs
code4romania/onghub pull request #101
Opened 2022-09-27 14:51 UTC by OlteanuCosmin

Fixed super-admin being able to delete his account (C4R-694) and the back button when viewing an application not working properly for the employee and admin (C4R-695).

2022-09-28 08:19 UTC, radulescuandrew requested changes

2022-09-28 08:19 UTC, radulescuandrew commented on frontend/src/pages/account/Account.tsx
> +        {role !== UserRole.SUPER_ADMIN && (
Doar employee putea sa iti stearga account din cate imi amintesc. Please recheck cu Andrei

2022-09-28 08:19 UTC, radulescuandrew commented on frontend/src/pages/application/Application.tsx
> +  const navigateBack = () => {
Ai testat toate scenariile? SuperAdmin, Admin, Employee care acceseaza aplicatia din AllApps/MyApps? Stiu ca era o problema aici de cand a implementat Florian si ajunsesem la un compromis.

2022-09-28 08:26 UTC, OlteanuCosmin commented on frontend/src/pages/account/Account.tsx
> +        {role !== UserRole.SUPER_ADMIN && (
Modificat, acum doar un employee poate sa-si stearga contul.

2022-09-28 08:26 UTC, OlteanuCosmin commented on frontend/src/pages/application/Application.tsx
> +  const navigateBack = () => {
Da, le-am testat pe toate. Employee si Admin sunt trimisi inapoi la My Apps, SuperAdmin inapoi la All Apps.

2022-09-29 09:27 UTC, dragos1195 commented on frontend/src/pages/application/Application.tsx
> +  const navigateBack = () => {
Nu merge corect pe urmatorul scenariu: 

All Apps -> Application -> Push Back button 

Result: Te intoarce pe /apps
Expected: Te intoarce pe all apps (de unde ai plecat)

2022-09-29 10:47 UTC, OlteanuCosmin commented
The back button will not work if the specific application page is loaded in a new tab (edge case?).

2022-09-29 11:11 UTC, OlteanuCosmin commented on frontend/src/pages/application/Application.tsx
> +  const navigateBack = () => {
Rezolvat.

2022-10-03 09:15 UTC, birloiflorian requested changes

2022-10-03 09:15 UTC, birloiflorian commented on frontend/src/pages/account/Account.tsx
> +  const { role } = useContext(AuthContext);
Ai useAuthContext mai sus de unde puteai sa iei rolul

2022-10-03 10:44 UTC, OlteanuCosmin commented on frontend/src/pages/account/Account.tsx
> +  const { role } = useContext(AuthContext);
Modificat.

2022-10-04 13:48 UTC, radulescuandrew approved these changes

2022-10-04 14:03 UTC, merged