feat: [C4R-709] sync organization on financial/data updates
code4romania/onghub pull request #103
Opened 2022-09-28 13:49 UTC by OlteanuCosmin

Update synced_on when an update is done on financial/open data.

2022-09-29 11:33 UTC, dragos1195 requested changes

2022-09-29 11:33 UTC, dragos1195 commented on backend/src/modules/organization/services/organization-report.service.ts
> +    organizationId: number,
Where is this used?

2022-09-29 11:33 UTC, dragos1195 commented on backend/src/modules/organization/services/organization-report.service.ts
> -    await this.reportService.update(reportId, {
why?

2022-09-29 11:33 UTC, dragos1195 commented on backend/src/modules/organization/services/organization-report.service.ts
> -    await this.reportService.update(reportId, {
Poate gresesc eu, dar daca nu primeste numberOfContractors sau numberOfVolunteers ii facem null.
Cand actualizez datele astea este posibil sa trimit doar una dintre ele?

Adica daca eu am completat anul trecut cu un numar de voluntari.
Anul asta pot sa completez partial (azi ceva, maine altceva) si sa zic doar numarul de contractori? 
Ca in update-ul de mai jos asta inseamna ca ii punem numberOfVolunteers null. 

E corect asa?

2022-09-29 11:47 UTC, OlteanuCosmin commented on backend/src/modules/organization/services/organization-report.service.ts
> +    organizationId: number,
Removed it.

2022-10-04 07:21 UTC, radulescuandrew commented on backend/src/modules/organization/services/organization-report.service.ts
> -    await this.reportService.update(reportId, {
@dragos1195 @OlteanuCosmin Ceva aici de facut?

2022-10-04 07:55 UTC, OlteanuCosmin commented on backend/src/modules/organization/services/organization-report.service.ts
> -    await this.reportService.update(reportId, {
I-am explicat eu fizic.

2022-10-04 13:45 UTC, radulescuandrew approved these changes

2022-10-04 13:45 UTC, merged