C4R-612 - Added email template with header and footer
code4romania/onghub pull request #105
Opened 2022-10-04 08:59 UTC by AndreeaMariaP

2022-10-04 12:41 UTC, radulescuandrew commented
De facut task, la toate apelurile de `sendMail` le lipseste `Subject`. Sa facem o lista de constante cu subject, content si variabile pentru fiecare mail. 

https://docs.google.com/spreadsheets/d/1VAX7_OgKedOYRmpCtJiHbuI2if-2t0ANje3UOiQDz1I/edit?usp=sharing aici sunt textele. 

@AndreeaMariaP avem nevoie de mai multe template-uri sau folosim doar unul in care bagam content?
@AndreeaMariaP cum inseram variabile in content?

2022-10-05 12:35 UTC, radulescuandrew requested changes

2022-10-05 13:31 UTC, OlteanuCosmin commented on backend/src/modules/application/services/application.service.ts
> +        template: MAIL_OPTIONS.ORGANIZATION_APPLICATION_REQUEST_DELETE.template,
Actualizat PR-ul (la destructuring, exista un caz in care a trebuit sa creez 2 constante).

2022-10-05 15:36 UTC, radulescuandrew commented on backend/src/modules/application/services/application.service.ts
> +        template: MAIL_OPTIONS.ORGANIZATION_APPLICATION_REQUEST_DELETE.template,
Nu vad asta in cod.

2022-10-05 16:03 UTC, OlteanuCosmin commented on backend/src/modules/application/services/application.service.ts
> +        template: MAIL_OPTIONS.ORGANIZATION_APPLICATION_REQUEST_DELETE.template,
Este in organization-request.service.ts. Am lasat comment-ul aici deoarece aici ai mentionat destructurarea.

2022-10-06 12:10 UTC, radulescuandrew approved these changes

2022-10-06 12:11 UTC, merged