[C4R-199] Dashboarding
code4romania/onghub pull request #109
Opened 2022-10-05 14:52 UTC by dragos1195

Dashboarding

2022-10-05 14:52 UTC, dragos1195 commented
Import ordering changes was done by Florian. :)

2022-10-07 08:21 UTC, radulescuandrew requested changes

2022-10-07 08:21 UTC, radulescuandrew commented on backend/src/modules/organization/controllers/organization.controller.ts
> +  @Roles(Role.ADMIN, Role.EMPLOYEE, Role.SUPER_ADMIN)
controlleru asta ar trebui sa fie doar pentru SUPER_ADMIN. 

Pentru ADMIN/EMPLOYEE avem ID organizatie in user. Poate sa ramana aici pentru SUPER_ADMIN si alt endpoint in org-profile (cred)

2022-10-07 08:21 UTC, radulescuandrew commented on backend/src/modules/organization/entities/organization.entity.ts
> +  financialStatus: OrganizationFinancialStatus;
asta se refera la lastUpdate? (pe care o sa-l faca Florian)

2022-10-07 08:21 UTC, radulescuandrew commented on backend/src/modules/organization/entities/organization-view.entity.ts
> +import { ViewColumn, ViewEntity } from 'typeorm';
@birloiflorian @dragos1195 nu inteleg utilitatea view-ului asta. Sa discutam 5 min

2022-10-07 08:21 UTC, radulescuandrew commented on backend/src/modules/organization/services/organization-statistics.service.ts
> +	public async getAllOrganizationsStatistics(): Promise<IAllOrganizationsStatistics> {
@birloiflorian lasam astea asa sau facem un modul de statistics si view-uri de sql? Pare ca tragem toate datele ca sa facem counturi.

2022-10-07 08:21 UTC, radulescuandrew commented on frontend/src/pages/dashboard/Dashboard.tsx
> +      useErrorToast('Eroare la preloarea datelor');
Preloare pe piept

2022-10-07 10:47 UTC, birloiflorian commented on backend/src/modules/organization/entities/organization-view.entity.ts
> +import { ViewColumn, ViewEntity } from 'typeorm';
Va fi sters in momentul in care integram completionStatus pe organizatie

2022-10-07 10:48 UTC, birloiflorian commented on backend/src/modules/organization/entities/organization.entity.ts
> +  financialStatus: OrganizationFinancialStatus;
Da, si ar trebui sa se numeasca completionStatus deoarece nu se refera doar la datele financiare.

2022-10-07 11:04 UTC, birloiflorian requested changes

2022-10-07 11:04 UTC, birloiflorian commented on frontend/src/components/statistics-card/StatisticsCardInfo.ts
> +export interface StatisticsCardInfo {
De ce am pus interfata asta intr-un fisier separat? Cred ca ar fi ok sa fie in acelasi fisier ca si componenta, la fel ca la ExetendedStatisticsCard.

2022-10-07 11:04 UTC, birloiflorian commented on frontend/src/pages/dashboard/Dashboard.tsx
> +      useErrorToast('Eroare la preloarea datelor');
+ ar trebui sa vina din internationalizare

2022-10-07 11:04 UTC, birloiflorian commented on frontend/src/pages/dashboard/Dashboard.tsx
> +          <p className="text-gray-800 font-titilliumBold text-3xl">Despre ONGHub</p>
Trebuie sa vina traducerea din internationalizare

2022-10-07 11:04 UTC, birloiflorian commented on frontend/src/pages/dashboard/SuperAdminDashboard.tsx
> +      useErrorToast('Eroare la preloarea datelor');
Internationalizare

2022-10-07 11:04 UTC, birloiflorian commented on frontend/src/pages/dashboard/constants/DashboardStatistics.constants.ts
> +    title: 'Numar mediu de utiliatori per organizatie',
Internationalizare in tot fisierul

2022-10-10 19:05 UTC, radulescuandrew requested changes

2022-10-11 10:46 UTC, birloiflorian commented on backend/src/modules/organization/entities/organization-statistics-view.entity.ts
> +@ViewEntity('OrganizationStatisticsView', {
Done

2022-10-11 10:59 UTC, birloiflorian commented on backend/src/modules/organization/controllers/organization.controller.ts
> +  getSuperAdminOrganizationStatusStatistics(
Done

2022-10-11 10:59 UTC, birloiflorian commented on backend/src/modules/organization/controllers/organization.controller.ts
> +  @Get('request-statistics')
Done

2022-10-11 12:36 UTC, birloiflorian commented on backend/src/modules/organization/services/organization-request.service.ts
> +  public async getOrganizationRequestStatistics(
Am creat un task separat: https://wearetribus.atlassian.net/browse/C4R-750

2022-10-11 13:18 UTC, birloiflorian commented on backend/src/modules/organization/services/organization-statistics.service.ts
> +      meanNumberOfUsers: Math.ceil(numberOfActiveOrganizations / numberOfUsers),
Done

2022-10-11 13:29 UTC, birloiflorian commented on backend/src/modules/organization/services/organization-statistics.service.ts
> +    return {
Done

2022-10-11 13:31 UTC, birloiflorian commented on frontend/src/common/router/Router.tsx
> +          <Route index element={role === UserRole.SUPER_ADMIN ? <SuperAdminDashboard /> : <Dashboard />}></Route>
Am modificar putin, dar e ok asa cum e.

2022-10-11 13:32 UTC, birloiflorian commented on frontend/src/pages/dashboard/SuperAdminDashboard.tsx
> +                count: statistics[key as keyof IAllOrganizationsStatistics],
@dragos1195

2022-10-11 13:46 UTC, birloiflorian commented on backend/src/modules/organization/enums/organization-request-statistics.enum.ts
> +  _30_DAYS = '30-days',
Done, il folosim doar pe cel de monthly, daily, yearly

2022-10-11 13:54 UTC, dragos1195 commented on frontend/src/pages/dashboard/SuperAdminDashboard.tsx
> +                count: statistics[key as keyof IAllOrganizationsStatistics],
Pentru ca statistics are tipul setat o interfata, vrea TS sa stie sigur ca ii dau o cheie care este din tipul interfetei.

2022-10-11 13:55 UTC, dragos1195 commented on frontend/src/common/router/Router.tsx
> +          <Route index element={role === UserRole.SUPER_ADMIN ? <SuperAdminDashboard /> : <Dashboard />}></Route>
Avem o situatie cand facem impartirea intr-o componenta, dar pentru ca nu facem nimic in plus in situatia asta, nu am impartit in ceva diferit.

2022-10-11 14:38 UTC, merged