Feature/c4 r 390 historization
code4romania/onghub pull request #110
Opened 2022-10-05 15:29 UTC by AndreeaMariaP

2022-10-05 15:47 UTC, radulescuandrew requested changes

2022-10-05 15:47 UTC, radulescuandrew commented on backend/src/modules/application/services/application-history.service.ts
> +import { HistoryEntitySubscriber } from '@anchan828/typeorm-history';
@AndreeaMariaP Move all subscribers into separate folder

2022-10-05 15:47 UTC, radulescuandrew commented on backend/src/modules/organization/entities/organization-history.entity.ts
> +  @OneToMany((type) => User, (user) => user.organization)
Remove OneToMany relations because the relation is on the Many side.

2022-10-05 15:47 UTC, radulescuandrew commented on backend/src/modules/application/services/application-history.service.ts
> +import { HistoryEntitySubscriber } from '@anchan828/typeorm-history';
And rename to `{name}.subscriber.ts`

2022-10-05 15:47 UTC, radulescuandrew commented on backend/src/modules/user/entities/user-history.entity.ts
> +    1. Creating a new organization will also create the admin (with role Admin)
Remove comment (also from user.entity)

2022-10-05 15:50 UTC, radulescuandrew commented
@AndreeaMariaP Also let's try to remove all relations and test again to prevent deletion problems in the future

2022-10-06 11:40 UTC, AndreeaMariaP commented on backend/src/modules/application/services/application-history.service.ts
> +import { HistoryEntitySubscriber } from '@anchan828/typeorm-history';
Moved subscribers to entities/subscribers and renamed them to {name}.subscriber.ts

2022-10-06 11:41 UTC, AndreeaMariaP commented on backend/src/modules/organization/entities/organization-history.entity.ts
> +  @OneToMany((type) => User, (user) => user.organization)
Removed relations

2022-10-06 11:41 UTC, AndreeaMariaP commented on backend/src/modules/user/entities/user-history.entity.ts
> +    1. Creating a new organization will also create the admin (with role Admin)
Removed comments

2022-10-06 13:42 UTC, radulescuandrew approved these changes

2022-10-06 13:42 UTC, merged