fix: multitude of fixes
code4romania/onghub pull request #112
Opened 2022-10-07 13:37 UTC by OlteanuCosmin

C4R-343: Multiple API calls are made but not all are needed
C4R-708: Short description text of an app is not displayed entirely
C4R-428: Error is missing when invalid data are entered
C4R-717: The app card's buttons are not displayed properly
C4R-480: Some fields accept duplicate values
C4R-703: Persistent toast
C4R-699: The button position should be set at bottom of apps
C4R-401: Error occurs when user tries to delete his account
C4R-528: Phone number field accepts duplicate values at employee

2022-10-10 19:57 UTC, radulescuandrew requested changes

2022-10-10 19:57 UTC, radulescuandrew commented on backend/src/modules/organization/services/organization.service.ts
> +    const organizationWithEmail = await this.organizationGeneralService.findOne(
Astea nu existau? 

@birloiflorian?

2022-10-10 19:57 UTC, radulescuandrew commented on backend/src/modules/organization/services/organization.service.ts
> +    const organizationWithAlias = await this.organizationGeneralService.findOne(
Ar merge sa facem un singur query cu `email` or `phone` or `alias` si sa cautam in array? Vreun motiv pentru care n-am facut asa? (putem sa punem task for the moment)

2022-10-10 19:57 UTC, radulescuandrew commented on backend/src/modules/user/services/user.service.ts
> +      const userEmailCheck = await this.findOne({
phoneCheck

2022-10-10 19:57 UTC, radulescuandrew commented on backend/src/modules/user/services/user.service.ts
>          case USER_ERRORS.GET.errorCode: {
```
case USER_ERRORS.GET.errorCode:
case USER_ERRORS.ACCESS.errorCode:
case USER_ERRORS.ALREADY_EXISTS_PHONE.errorCode:
throw new BadRequestException(err); 
``` 
Merge asa ca sa nu mai scriem 100 linii?

2022-10-10 19:57 UTC, radulescuandrew commented on backend/src/modules/user/services/user.service.ts
> +          throw new BadRequestException({
La fel ca celalalt comment

2022-10-10 19:57 UTC, radulescuandrew commented on frontend/src/pages/create-organziation/configs/CreateOrganizationUserConfig.ts
> +        value: 5,
Why?

2022-10-10 19:57 UTC, radulescuandrew commented on frontend/src/pages/users/components/UserCreate/UserCreate.tsx
> +          const updateError: any = createUserMutation.error;
@birloiflorian Ar trebui sa le mapam ca in CREATE_ORGANIZATION_ERRORS?

2022-10-11 08:00 UTC, OlteanuCosmin commented on frontend/src/pages/create-organziation/configs/CreateOrganizationUserConfig.ts
> +        value: 5,
Nu corespundea cu valoarea din BE.

2022-10-11 08:13 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
>          case USER_ERRORS.GET.errorCode: {
Modificat.

2022-10-11 08:13 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
> +          throw new BadRequestException({
Modificat.

2022-10-12 11:21 UTC, birloiflorian approved these changes

2022-10-12 11:22 UTC, merged