feat: added a shell script to backup remote db and restore into local db
code4romania/onghub pull request #118
Opened 2022-10-12 11:39 UTC by OlteanuCosmin

2022-10-12 12:52 UTC, radulescuandrew requested changes

2022-10-12 12:52 UTC, radulescuandrew commented on backend/docs/database-backup-remote-restore-local.sh
> +echo What is your remote database?
remote db URL

2022-10-12 12:52 UTC, radulescuandrew commented on backend/docs/database-backup-remote-restore-local.sh
> +echo Name your file
Nu cred ca e nevoie din moment ce il importi tot tu

2022-10-12 12:52 UTC, radulescuandrew commented on backend/docs/database-backup-remote-restore-local.sh
> +pg_dump -h $REMOTE_DATABASE -U $USER_NAME -f $FILE_NAME.sql
Asta nu o sa ceara parola?

2022-10-12 12:52 UTC, radulescuandrew commented on backend/docs/database-backup-remote-restore-local.sh
> +echo What is your docker container id?
"Enter your database container id (use `docker ps` to find)"

2022-10-12 13:05 UTC, OlteanuCosmin commented on backend/docs/database-backup-remote-restore-local.sh
> +pg_dump -h $REMOTE_DATABASE -U $USER_NAME -f $FILE_NAME.sql
Ba da. In momentul in care se ajunge la comanda si se executa, se cere parola.

2022-10-12 13:14 UTC, OlteanuCosmin commented on backend/docs/database-backup-remote-restore-local.sh
> +echo What is your remote database?
Redenumit.

2022-10-12 13:14 UTC, OlteanuCosmin commented on backend/docs/database-backup-remote-restore-local.sh
> +echo What is your docker container id?
Redenumit.

2022-10-13 08:51 UTC, radulescuandrew approved these changes

2022-10-13 08:51 UTC, merged