Feature[C4R-777] CRUD Practice Programs
code4romania/onghub pull request #120
Opened 2022-10-14 15:08 UTC by birloiflorian

2022-10-18 07:20 UTC, dragos1195 requested changes

2022-10-18 07:20 UTC, dragos1195 commented on backend/src/modules/practice-program/services/practice-program.service.ts
> +      // 6. check if undetermined flad and end date have correct values
flag*

2022-10-19 09:44 UTC, radulescuandrew commented on backend/src/shared/entities/city.entity.ts
> +  @OneToMany(() => PracticeProgram, (practicePrgram) => practicePrgram.location)
E necesar asta aici? 

```If you only care about the @ManyToOne relationship, you can define it without having @OneToMany on the related entity. Where you set @ManyToOne - its related entity will have "relation id" and foreign key.```

2022-10-19 09:45 UTC, radulescuandrew reviewed
1 thing

2022-10-19 10:42 UTC, birloiflorian commented on backend/src/modules/practice-program/services/practice-program.service.ts
> +      // 6. check if undetermined flad and end date have correct values
Fixed

2022-10-19 10:42 UTC, birloiflorian commented on backend/src/shared/entities/city.entity.ts
> +  @OneToMany(() => PracticeProgram, (practicePrgram) => practicePrgram.location)
Nu este necesar, a fost scoasa.

2022-10-19 10:43 UTC, merged