feat: [C4R-775] added hover to app name and short description
code4romania/onghub pull request #121
Opened 2022-10-17 11:48 UTC by OlteanuCosmin

C4R-746 and C4R-785: selected tab remains in same state when user clicks on 'back' on all apps/users page
C4R-751: back button doesn't work properly on create app page
C4R-775: added hover to app name and short description (solves C4R-734 and C4R-708)
C4R-784: scroll bars are duplicated on windows on every page

2022-10-17 15:19 UTC, dragos1195 requested changes

2022-10-17 15:19 UTC, dragos1195 commented on frontend/src/index.css
> +  -webkit-line-clamp: 2;
Should be checked on multiple browsers.

2022-10-17 15:19 UTC, dragos1195 commented on frontend/src/pages/apps-store/AllApplications.tsx
> +                  tab.href === location.pathname.split('/')[2]
This should be in a UseEffect and we should use the selectedTab.
You should also check against other components with tabs.

2022-10-17 15:19 UTC, dragos1195 commented on frontend/src/pages/users/Users.tsx
> +                tab.href === location.pathname.split('/')[2]
Here also,

2022-10-19 13:22 UTC, OlteanuCosmin commented on frontend/src/index.css
> +  -webkit-line-clamp: 2;
Tested on Chrome, Firefox and Safari; works properly on all of them.

2022-10-20 11:26 UTC, OlteanuCosmin commented on frontend/src/pages/apps-store/AllApplications.tsx
> +                  tab.href === location.pathname.split('/')[2]
Added additional useEffect.

2022-10-21 13:28 UTC, merged