feat: [C4R-812] - CRUD on civic center services
code4romania/onghub pull request #129
Opened 2022-10-20 06:51 UTC by AndreeaMariaP

[C4R-812](https://wearetribus.atlassian.net/browse/C4R-812) - CRUD Centrul Civic
[C4R-788](https://wearetribus.atlassian.net/browse/C4R-788) - Parent task

2022-10-21 13:04 UTC, birloiflorian requested changes

2022-10-21 13:04 UTC, birloiflorian commented on backend/src/modules/practice-program/services/civic-center-service.service.ts
> +        ...(civicCenterServicePayload.hasOnlineAccess
Acum ca ma gandesc mai bine nu stiu daca are sens sa le punem asa conditional aici cel putin, adica le salvam asa cum vin. Oricum avem validare mai sus legat pentru fiecare tip de access. O alta intrebare ar fi daca ar trebui validam scenariul in care pe payload pot veni mai mult de unul din flag-uri pe true (lucru care nu ar trebui sa fie posibil), din ce vad acum putem sa le avem pe toate pe 'true'.

2022-10-21 13:04 UTC, birloiflorian commented on backend/src/modules/practice-program/services/civic-center-service.service.ts
> +        ...(civicCenterServicePayload.hasOnlineAccess
La fel ca mai sus. In plus, ne dorim ca in cazul in care se schimba flag-ul pe tipul de access sa stergem datele pentru tipul ala de access sau sa le pastram in cazul in care vrea sa revina la tipul ala ulterior si sa le aiba deja completate?

2022-10-21 13:24 UTC, AndreeaMariaP commented on backend/src/modules/practice-program/services/civic-center-service.service.ts
> +        ...(civicCenterServicePayload.hasOnlineAccess
Daca un parametru de access vine fals, nu vad de ce am salva ceilalti parametrii dependenti.
In documentatie scrie `1-3 types on access (minimum one is mandatory)`

2022-10-21 13:31 UTC, AndreeaMariaP commented on backend/src/modules/practice-program/dto/create-civic-center-service.dto.ts
> +  @MinDate(new Date())
Fixed

2022-10-24 15:05 UTC, birloiflorian commented on backend/src/modules/practice-program/services/civic-center-service.service.ts
> +        ...(civicCenterServicePayload.hasOnlineAccess
Rezolvam la crearea formularului.

2022-10-24 15:05 UTC, birloiflorian approved these changes

2022-10-24 15:11 UTC, merged