feat: [C4R-817] public send mail function
code4romania/onghub pull request #130
Opened 2022-10-20 12:56 UTC by OlteanuCosmin

Supports only mails sent to contact mail for now, will be changed later if needed.

2022-10-21 12:26 UTC, birloiflorian requested changes

2022-10-21 12:26 UTC, birloiflorian commented on backend/src/mail/services/mail.service.ts
> +    let from: string | Address;
Aici am putea folosi ternary operator

2022-10-21 12:26 UTC, birloiflorian commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +import { ISendMailOptions } from '@nestjs-modules/mailer';
Unused import?

2022-10-21 13:04 UTC, OlteanuCosmin commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +import { ISendMailOptions } from '@nestjs-modules/mailer';
Removed unused imports.

2022-10-21 13:04 UTC, OlteanuCosmin commented on backend/src/mail/services/mail.service.ts
> +    let from: string | Address;
Replaced with ternary operator.

2022-10-21 13:29 UTC, radulescuandrew commented on backend/src/modules/_publicAPI/public-api-send-mail.service.ts
> +  public async sendMail(mailOptions: ContactMailDto): Promise<void> {
Nu cred ca e necesar service asta. Poti sa injectezi mailService direct in controller momentan (pana facem event based)

2022-10-21 13:47 UTC, OlteanuCosmin commented on backend/src/modules/_publicAPI/public-api-send-mail.service.ts
> +  public async sendMail(mailOptions: ContactMailDto): Promise<void> {
Sters service-ul.

2022-10-24 09:10 UTC, birloiflorian approved these changes

2022-10-31 08:13 UTC, OlteanuCosmin commented on backend/src/modules/_publicAPI/public-api-send-mail.service.ts
> +  public async sendMail(mailOptions: ContactMailDto): Promise<void> {
Sters import-ul din modul.

2022-10-31 11:42 UTC, merged