Feature[C4R-713] Practice Program list and actions
code4romania/onghub pull request #135
Opened 2022-10-27 09:40 UTC by birloiflorian

- [C4R-713](https://wearetribus.atlassian.net/browse/C4R-713) Practice program list view with
- [C4R-764](https://wearetribus.atlassian.net/browse/C4R-764) Practice program actions (delete/edit/enable/disable)

2022-10-27 10:03 UTC, AndreeaMariaP requested changes

2022-10-27 10:03 UTC, AndreeaMariaP commented on frontend/src/pages/application/components/ApplicationDetails.tsx
> +                        className="save-button pl-8 pr-8 flex gap-4 sm:text-sm lg:text-base text-xs"
pl-8 pr-8 se pot scrie usor px-8, e mai simplu de modficat dupa daca e cazul (in loc sa modifici in 2 locuri, modifici in 1)

2022-10-27 10:03 UTC, AndreeaMariaP commented on frontend/src/pages/pactice-program/components/PracticeProgramContent.tsx
> +  const calculatePerid = () => {
typo calculatePerid

2022-10-27 11:17 UTC, radulescuandrew requested changes

2022-10-27 11:17 UTC, radulescuandrew commented on backend/src/modules/application/entities/application.entity.ts
> +  pullingType: ApplicationPullingType;
managementModule, managementCeva, nu am deloc inspiratie 🗡️ 😄 

Practic asta e modul prin care vedem daca o aplicatie are o arie separata de management. 

`externalManagementType`, `externalConfigurationType`? nu am inspiratie deloc

2022-10-27 11:17 UTC, radulescuandrew commented on frontend/src/pages/apps-store/components/AddApplicationConfig.ts
> +export const PullingTypeOptions = [
ApplicationsExternalConfigurationZoneOptions? 😄 😆

2022-10-27 11:17 UTC, radulescuandrew commented on frontend/src/services/application/Application.service.ts
> +    payload.append('pullingType', pullingType.value);
de ce nu intra in `data` si asta?

2022-10-28 09:17 UTC, birloiflorian commented on backend/src/modules/practice-program/constants/errors.constants.ts
> +    message: 'Error while updateing status',
Fixed.

2022-10-28 09:17 UTC, birloiflorian commented on frontend/src/pages/pactice-program/components/PracticeProgramContent.tsx
> +  const calculatePerid = () => {
Fixed

2022-10-28 09:17 UTC, birloiflorian commented on backend/src/modules/practice-program/services/practice-program.service.ts
> +        where: where,
Fixed.

2022-10-28 09:20 UTC, AndreeaMariaP approved these changes

2022-10-31 11:33 UTC, merged