feat: [C4R-917] feedback entity addition and CRUD
code4romania/onghub pull request #137
Opened 2022-11-01 09:28 UTC by OlteanuCosmin

[C4R-917](https://wearetribus.atlassian.net/browse/C4R-917)

2022-11-02 09:14 UTC, birloiflorian requested changes

2022-11-02 09:14 UTC, birloiflorian commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +  public async findManyPaginated(
aici ar trebui sa folosim getManyPaginated nu sa rescriem.

2022-11-02 09:14 UTC, birloiflorian commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +    const civicCenterServices = await this.civicCenterServiceService.findAll({
Nu avem nevoie de civicCenterServiceService aici. Cand cautam in feedback putem sa avem asa:
```
this.feedbackRepository.find({
      where: {
        civicCenterService: {
          organizationId: options.organizationId
          }
      },
}
```

2022-11-02 09:14 UTC, birloiflorian commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +      await this.findOne(id);
Aici chiar avem nevoie de findOne? adica daca nu o gaseste ar trebui sa intoarca eroare oricum.

2022-11-02 09:20 UTC, radulescuandrew requested changes

2022-11-02 09:20 UTC, radulescuandrew commented on backend/src/app.module.ts
> +    CivicCenterServiceModule,
The module can be named "CivicCenterModule"

2022-11-02 09:20 UTC, radulescuandrew commented on backend/src/app.module.ts
> +    CivicCenterServiceModule,
Same for controller and services

2022-11-02 09:20 UTC, radulescuandrew commented on backend/src/modules/civic-center-service/controllers/feedback.controller.ts
> +@Controller('feedback')
ar trebui sa avem o ruta comuna pentru "civic-center", e.g. 'civic-center/feedback'

2022-11-02 10:08 UTC, OlteanuCosmin commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +      await this.findOne(id);
Imi intoarce 200 daca nu adaug acel findOne.

2022-11-02 12:32 UTC, OlteanuCosmin commented on backend/src/modules/civic-center-service/controllers/feedback.controller.ts
> +@Controller('feedback')
Schimbat rutele.

2022-11-02 12:33 UTC, OlteanuCosmin commented on backend/src/app.module.ts
> +    CivicCenterServiceModule,
Renamed the files, with the exception of the service. There is already a class called CivicCenterService (the entity).

2022-11-02 12:34 UTC, OlteanuCosmin commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +  public async findManyPaginated(
Modificat pentru a folosi getManyPaginated.

2022-11-02 12:34 UTC, OlteanuCosmin commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +    const civicCenterServices = await this.civicCenterServiceService.findAll({
Rescris functia fara utilizarea unui serviciu secundar.

2022-11-03 09:47 UTC, birloiflorian requested changes

2022-11-03 09:47 UTC, birloiflorian commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +      const {
de ce faci destructuring aici?

2022-11-03 09:47 UTC, birloiflorian commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +    const organizationServicesFeedbacks = await this.feedbackRepository.getMany(
Nu avem nevoie de asta conditia de 
```
where: {
          civicCenterService: {
            organizationId: user.organizationId,
          },
        },
```
trebuie sa fie in get many paginated

2022-11-03 12:12 UTC, OlteanuCosmin commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +      const {
Scos destructuring-ul.

2022-11-03 12:13 UTC, OlteanuCosmin commented on backend/src/modules/civic-center-service/services/feedback.service.ts
> +    const organizationServicesFeedbacks = await this.feedbackRepository.getMany(
Mutat conditia.

2022-11-04 13:16 UTC, radulescuandrew approved these changes

2022-11-04 13:16 UTC, merged