feat: [C4R-920] added feedback table with pagination
code4romania/onghub pull request #138
Opened 2022-11-02 12:58 UTC by OlteanuCosmin

[C4R-920](https://wearetribus.atlassian.net/browse/C4R-920)

2022-11-07 11:52 UTC, dragos1195 requested changes

2022-11-07 11:52 UTC, dragos1195 commented on frontend/src/pages/civic-center-service/CivicCenterServices.tsx
> +    href: SERVICE_TABS.find((item) => item.id === 0)?.href || '',
Why not a single find for the initial state?

2022-11-07 12:03 UTC, birloiflorian commented
De ce avem comis, package-lock aici?

2022-11-07 12:11 UTC, birloiflorian requested changes

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +  "civic-center": {
inconsitenta intre '-' si '_'.

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +    "my_services": "Serviciile mele",
daca asta este "title" ar trebui sa fie numit ca atare

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +    "table_name": "Feedback",
"title"

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/pages/civic-center-service/components/feedback/FeedbackList.tsx
> +        },
putem sa punem eroare din useEffect aici in onError. cred ca este mai clar

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/pages/civic-center-service/components/feedback/components/FeedbackViewModal.tsx
> +interface ConfirmationModalProps {
Numele interfetei nu este consitent cu numele componentei

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/pages/civic-center-service/components/feedback/components/FeedbackViewModal.tsx
> +                        Detalii feedback
internationalizare

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/pages/civic-center-service/components/feedback/components/FeedbackViewModal.tsx
> +                        Detalii feedback
te rog sa verifici in tot fisierul

2022-11-07 12:11 UTC, birloiflorian commented on frontend/src/services/civic-center-service/CivicCenterService.service.ts
> +export const removeFeedback = async (id: number): Promise<any> => {
sa evitam pe cat posibil sa folosim ```any``` ca type.

2022-11-07 13:45 UTC, OlteanuCosmin commented on frontend/src/pages/civic-center-service/CivicCenterServices.tsx
> +    href: SERVICE_TABS.find((item) => item.id === 0)?.href || '',
You're referring to using only one find to get both 'href' and 'name'?

2022-11-07 13:48 UTC, OlteanuCosmin commented on frontend/src/services/civic-center-service/CivicCenterService.service.ts
> +export const removeFeedback = async (id: number): Promise<any> => {
Modificat in `void`

2022-11-07 13:49 UTC, OlteanuCosmin commented on frontend/src/pages/civic-center-service/components/feedback/components/FeedbackViewModal.tsx
> +                        Detalii feedback
Adaugat internationalizare in tot fisierul.

2022-11-07 13:49 UTC, OlteanuCosmin commented on frontend/src/pages/civic-center-service/components/feedback/components/FeedbackViewModal.tsx
> +interface ConfirmationModalProps {
Modificat numele interfetei sa corespunda cu numele componentei.

2022-11-07 13:49 UTC, OlteanuCosmin commented on frontend/src/pages/civic-center-service/components/feedback/FeedbackList.tsx
> +        },
Mutat eroarea din useEffect in onDelete.

2022-11-07 13:49 UTC, OlteanuCosmin commented on frontend/src/assets/locales/ro/translation.json
> +    "table_name": "Feedback",
Redenumit.

2022-11-07 13:49 UTC, OlteanuCosmin commented on frontend/src/assets/locales/ro/translation.json
> +    "my_services": "Serviciile mele",
Redenumit.

2022-11-07 13:50 UTC, OlteanuCosmin commented on frontend/src/assets/locales/ro/translation.json
> +  "civic-center": {
Modificat.

2022-11-07 13:54 UTC, OlteanuCosmin commented
> De ce avem comis, package-lock aici?

Uncommitted.

2022-11-08 09:27 UTC, OlteanuCosmin commented on frontend/src/pages/civic-center-service/CivicCenterServices.tsx
> +    href: SERVICE_TABS.find((item) => item.id === 0)?.href || '',
Updated to use only one find.

2022-11-09 08:51 UTC, merged