feat: [C4R-902] count practive programs and ongs with app
code4romania/onghub pull request #140
Opened 2022-11-03 13:16 UTC by OlteanuCosmin

[C4R-902](https://wearetribus.atlassian.net/browse/C4R-902)

2022-11-07 11:42 UTC, dragos1195 requested changes

2022-11-07 11:42 UTC, dragos1195 commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +  @Get('landing-counters')
Should be able to handle multiple pulling types.

2022-11-07 11:42 UTC, dragos1195 commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +      activePracticePrograms: await this.practiceProgramService.countActive(),
"activePracticePrograms" should be renamed to be generic.

2022-11-07 11:42 UTC, dragos1195 commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +      activePracticePrograms: await this.practiceProgramService.countActive(),
Should be in a separate service -> StatisticsService.

2022-11-07 11:42 UTC, dragos1195 commented on backend/src/modules/application/services/application.service.ts
> +        pullingType: ApplicationPullingType.CIVIC_SERVICE,
In a different service maybe and with pullingType as a parameter.

2022-11-07 11:42 UTC, dragos1195 commented on backend/src/modules/organization/controllers/organization-application.controller.ts
> +import { Public } from 'src/common/decorators/public.decorator';
?

2022-11-07 11:42 UTC, dragos1195 commented on backend/src/modules/practice-program/services/practice-program.service.ts
> +  public async countActive(): Promise<number> {
Different service with pullingType as param.

2022-11-07 12:00 UTC, birloiflorian requested changes

2022-11-07 12:00 UTC, birloiflorian commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +      activePracticePrograms: await this.practiceProgramService.countActive(),
@dragos1195 daca mutam in statistics service sa ne asiguram ca construim ruta ```statistics/practice-programs```

2022-11-07 13:04 UTC, OlteanuCosmin commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +  @Get('landing-counters')
Can handle multiple pulling types.

2022-11-07 13:05 UTC, OlteanuCosmin commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +      activePracticePrograms: await this.practiceProgramService.countActive(),
Changed to "activeItems".

2022-11-07 13:05 UTC, OlteanuCosmin commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +      activePracticePrograms: await this.practiceProgramService.countActive(),
Mutat in StatisticsService si redenumit ruta in `statistics/landing-counters`

2022-11-07 13:06 UTC, OlteanuCosmin commented on backend/src/modules/application/services/application.service.ts
> +        pullingType: ApplicationPullingType.CIVIC_SERVICE,
Mutat si adaugat pulling type ca parametru.

2022-11-07 13:16 UTC, OlteanuCosmin commented on backend/src/modules/_publicAPI/public-api.controller.ts
> +  @Get('landing-counters')
Can handle multiple pulling types.

2022-11-07 13:17 UTC, OlteanuCosmin commented on backend/src/modules/organization/controllers/organization-application.controller.ts
> +import { Public } from 'src/common/decorators/public.decorator';
Sters import-ul.

2022-11-07 13:17 UTC, OlteanuCosmin commented on backend/src/modules/application/services/application.service.ts
> +  public async countActiveWithCCApplication(): Promise<number> {
Actualizat.

2022-11-08 08:16 UTC, OlteanuCosmin commented on backend/src/modules/practice-program/services/practice-program.service.ts
> +  public async countActive(): Promise<number> {
Done.

2022-11-08 08:29 UTC, dragos1195 requested changes

2022-11-08 08:29 UTC, dragos1195 commented on backend/src/modules/application/services/application.service.ts
> +    pullingType: string,
Shouldn't be type of an Enum?

2022-11-08 08:29 UTC, dragos1195 commented on backend/src/modules/statistics/controllers/statistics.controller.ts
> +    @Query('pulling_type') pullingType: string,
Type enum

2022-11-08 08:29 UTC, dragos1195 commented on backend/src/modules/statistics/services/statistics.service.ts
> +  public async getLandingCounters(pullingType: string): Promise<object> {
Type enum

2022-11-08 08:29 UTC, dragos1195 commented on backend/src/modules/statistics/services/statistics.service.ts
> +    }
Add a default that throws an error

2022-11-08 08:29 UTC, dragos1195 commented on backend/src/modules/statistics/services/statistics.service.ts
> +  public async getLandingCounters(pullingType: string): Promise<object> {
Return type should be a promise of an interface.

2022-11-08 09:14 UTC, OlteanuCosmin commented on backend/src/modules/application/services/application.service.ts
> +    pullingType: string,
Modificat in type Enum.

2022-11-08 09:14 UTC, OlteanuCosmin commented on backend/src/modules/statistics/controllers/statistics.controller.ts
> +    @Query('pulling_type') pullingType: string,
Modificat.

2022-11-08 09:15 UTC, OlteanuCosmin commented on backend/src/modules/statistics/services/statistics.service.ts
> +  public async getLandingCounters(pullingType: string): Promise<object> {
Modificat.

2022-11-08 09:15 UTC, OlteanuCosmin commented on backend/src/modules/statistics/services/statistics.service.ts
> +    }
Added default case and try catch block.

2022-11-08 09:15 UTC, OlteanuCosmin commented on backend/src/modules/statistics/services/statistics.service.ts
> +  public async getLandingCounters(pullingType: string): Promise<object> {
Modified.

2022-11-09 08:50 UTC, merged