fix: [TEO-250] Move lambda "preauthentication check" to terraform
code4romania/onghub pull request #296
Opened 2023-03-01 12:20 UTC by radulescuandrew

- remove serverless lambda folder
- create new lambda definition in lambda.tf 
- link it from cognito.tf
- replace hardcoded values from the function with ENV variables

2023-03-02 12:28 UTC, andreiio requested changes

2023-03-02 12:28 UTC, andreiio commented on terraform/lambda.tf
> +}
cel mai probabil n-o să putem rula `npm install` pe terraform cloud. if it fails, a good backup option e să commit node_modules în git.

2023-03-02 12:28 UTC, andreiio commented on terraform/lambda.tf
> +      onghub_api_url : "https://${aws_apprunner_service.backend.service_url}"
Nu putem să folosim aceste două variable aici pentru că intrăm într-o logică circulară:

aws_cognito_user_pool_client.onghub_client.id:
```
Error: Cycle: aws_cognito_user_pool_client.onghub_client, 
aws_lambda_function.login_pre_authentication_check, aws_cognito_user_pool.pool
```

aws_apprunner_service.backend.service_url:
```
Error: Cycle: aws_cognito_user_pool_client.onghub_client, aws_apprunner_service.backend, aws_lambda_function.login_pre_authentication_check, aws_cognito_user_pool.pool
```

Cred că ar trebui să le pasăm ca variabile în terraform cloud.

2023-03-02 15:33 UTC, radulescuandrew commented on terraform/lambda.tf
> +      onghub_api_url : "https://${aws_apprunner_service.backend.service_url}"
OK.

2023-03-02 15:34 UTC, radulescuandrew commented on terraform/lambda.tf
> +}
OK, both ways. Daca nu merge punem direct functia. let me know

2023-03-06 10:44 UTC, andreiio approved these changes

2023-03-06 10:44 UTC, merged