feat[C4R-285] File Upload / Upload Organization Logo
code4romania/onghub pull request #33
Opened 2022-07-27 11:03 UTC by birloiflorian

[C4R-285]

- File Upload service
- Upload enpoint organization (handler for logo and organization statute)
- Update logo

2022-07-27 13:06 UTC, OlteanuCosmin approved these changes

2022-08-03 11:09 UTC, radulescuandrew requested changes

2022-08-03 11:09 UTC, radulescuandrew commented on frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
> +    const rows = await readXlsxFile(file);
Facem read la file in frontend?

2022-08-03 11:09 UTC, radulescuandrew commented on frontend/src/pages/organization/interfaces/Investor.interface.ts
> +  link: string | null;
Astea cred ca trebuie sa fie ID peste tot cum ziceam cu presignedURL ala

2022-08-03 12:41 UTC, birloiflorian commented on backend/src/modules/organization/organization.controller.ts
> +    return this.organizationService.upload(id, files);
https://wearetribus.atlassian.net/browse/C4R-352

2022-08-04 13:20 UTC, birloiflorian commented on backend/src/shared/controllers/shared.controller.ts
> +      'static/Lista_parteneri_2021.xlsx',
https://wearetribus.atlassian.net/browse/C4R-358

2022-08-04 13:36 UTC, radulescuandrew approved these changes

2022-08-04 13:36 UTC, radulescuandrew commented on backend/src/modules/organization/organization.controller.ts
> +  @ApiConsumes('multipart/form-data')
Leftover?

2022-08-04 13:36 UTC, radulescuandrew commented on backend/src/modules/organization/services/organization-report.service.ts
> +    const investor = await this.investorRepository.get({
Vad ca peste tot avem aceeasi logica de facem GET din repository si daca nu exista aruncam eroare. Ma gandesc ca erorile ar trebui controlate din service-urile lor, de ex. 

`investorService.getById()` isi arunca propria eroare de INVESTOR_ERRORS.GET. 

Lasa doar TODO de refactor ca sa nu exageram acum dar ca pattern poate ne ajuta pe viitor daca o sa reutilizam functia.

2022-08-04 13:36 UTC, radulescuandrew commented on backend/src/modules/organization/services/organization.service.ts
> +    const organization = await this.organizationRepository.get({
Acelasi lucru ca mai sus.

2022-08-04 14:17 UTC, merged