refactor: bug fixes for NGO General
code4romania/onghub pull request #34
Opened 2022-07-29 07:47 UTC by OlteanuCosmin

2022-07-29 08:41 UTC, radulescuandrew requested changes

2022-07-29 08:41 UTC, radulescuandrew commented on frontend/src/common/helpers/format.helper.ts
> +export const emptyStringToNull = (obj: any): any => {
Asta nu face doar emptyStringToNull, ci orice valoare falsy (false, 0, undefined, '') o sa devina null. Apelata pe organizationGeneral e safe? 

Care e usecase-ul?

De ce nu folosim map?

2022-07-29 08:41 UTC, radulescuandrew commented on frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneralConfig.ts
> +        message: 'Invalid format',
"Email format is invalid"

2022-07-29 08:41 UTC, radulescuandrew commented on frontend/src/pages/organization/enums/OrganizationType.enum.ts
> +  federation: 'Federatie',
Ar avea sens aici sa folosim enum-ul si pentru naming, unde cheia e enum-ul  pentru strong typing. Pune un TODO in cod pentru asta te rog.

export const OrganizationTypeNaming = {
   OrganizationTypeEnum.ASSOCIATION: 'Asociatie'
   ....
}

2022-07-29 08:41 UTC, radulescuandrew commented on frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneralConfig.ts
> +      collection: rangeOfYears(1800),
1800?

2022-07-29 08:44 UTC, OlteanuCosmin commented on frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneralConfig.ts
> +      collection: rangeOfYears(1800),
Asta au discutat ieri Dragos is Stefania.

2022-07-29 08:45 UTC, OlteanuCosmin commented on frontend/src/common/helpers/format.helper.ts
> +export const emptyStringToNull = (obj: any): any => {
Asta e adaugat de Dragos. Pot sa ma uit eu daca e.

2022-07-29 10:29 UTC, radulescuandrew commented on frontend/src/common/helpers/format.helper.ts
> +export const emptyStringToNull = (obj: any): any => {
Da, te rog.

@dragos1195 sa ne dai si inputul tau

2022-08-01 07:29 UTC, dragos1195 commented on frontend/src/common/helpers/format.helper.ts
> +export const emptyStringToNull = (obj: any): any => {
Daca un field este empty string devine null. 
Este folosit pentru a putea transforma valorile empty string (din forms, oricare ar fi ele) in null pentru ca backend-ul sa le stearga. 

Backend-ul primeste empty string ca valori valide in multe situatii, de aceea am convenit cu Florian cand am lucrat pe integrare sa trimit null in loc de empty string.

2022-08-02 08:10 UTC, radulescuandrew approved these changes

2022-08-02 08:10 UTC, merged