fixes: NGO Activity
code4romania/onghub pull request #49
Opened 2022-08-09 11:27 UTC by OlteanuCosmin

C4R-374: missing error when not having any domain selected
C4R-378: city list should return exact value
C4R-379: validation issues on FE (regions, federations, coalitions, international organization, branches)
C4R-383: branches field does not get saved on BE

2022-08-09 14:54 UTC, birloiflorian requested changes

2022-08-09 14:54 UTC, birloiflorian commented on backend/src/shared/controllers/nomenclatures.controller.ts
> +@UseInterceptors(ClassSerializerInterceptor)
De ce am scos CacheInterceptor si commentat decoratorul de ApiQuery?

2022-08-09 16:26 UTC, OlteanuCosmin commented on backend/src/shared/controllers/nomenclatures.controller.ts
> +@UseInterceptors(ClassSerializerInterceptor)
Am uitat sa-l readaug dupa ce am testat, my bad. Iar decoratorul trebuia sa-l sterg: nu are nici o functionalitate in acel endpoint, doar adauga 2 campuri noi care oricum nu pot fi folosite.

2022-08-11 08:12 UTC, birloiflorian approved these changes

2022-08-11 12:06 UTC, dragos1195 commented on backend/src/modules/organization/services/organization.service.ts
> +      if (createOrganizationDto.activity.branches.length === 0) {
Should add a "?" after "branches" in case is null or undefined.

2022-08-11 13:34 UTC, merged