[C4R-17] Create NGO Request
code4romania/onghub pull request #54
Opened 2022-08-10 12:15 UTC by dragos1195

Create NGO Request

Tasks:

Create NGO Profile:
C4R-17
C4R-62
C4R-63
C4R-64

Requests
C4R-389

++ Multiple mappings for NGO Request

2022-08-10 12:42 UTC, birloiflorian requested changes

2022-08-10 12:42 UTC, birloiflorian commented on frontend/src/pages/create-organziation/CreateOrganization.tsx
> +  const [loading, setLoading] = useState(false);
Ar trebui sa folosim loading din use-query

2022-08-10 12:50 UTC, radulescuandrew requested changes

2022-08-10 12:50 UTC, radulescuandrew commented on backend/src/modules/requests/services/requests.service.ts
> +        { phone: createReqDto.admin.phone },
E de ajuns doar email. 
Am scos "phone" **unique** ca devine prea complicat.

2022-08-10 12:50 UTC, radulescuandrew commented on backend/src/modules/requests/constants/requests-errors.constants.ts
> +      message: 'Request already made.',
"There is already a pending request with the same admin email address" sa intelegem cand vine eroarea

2022-08-10 12:50 UTC, radulescuandrew commented on backend/src/modules/requests/services/requests.service.ts
> +      where: [
Si trebuie sa fie pending, altfel requesturile vechi rejected vor fi returnate.

2022-08-10 12:50 UTC, radulescuandrew commented on backend/src/modules/requests/services/requests.service.ts
> +      throw new BadRequestException({
OrganizationService ar trebui sa faca handle la propriile erori.

Ori scoatem try/catch ori pe catch ar trebui sa aruncam eroarea care vine din orgService.

2022-08-10 12:50 UTC, radulescuandrew commented on backend/src/modules/requests/dto/create-request-user.dto.ts
> +export class CreateRequestUserDto {
Mai e folosit?

2022-08-10 12:50 UTC, radulescuandrew commented on backend/src/modules/user/services/user.service.ts
> +  public async findOne(options: FindOneOptions): Promise<User> {
E folosita?

2022-08-10 12:50 UTC, radulescuandrew commented on backend/src/shared/services/anaf.service.ts
> +    if (anafData && anafData.length === 0) {
Cred ca lipseste `if(!anafData)`

2022-08-10 12:50 UTC, radulescuandrew commented on frontend/src/services/API.ts
>    const user = await Auth.currentAuthenticatedUser();
try/catch aci, daca nu e auth trimitem request fara bearer

2022-08-10 12:50 UTC, radulescuandrew commented on frontend/src/services/nomenclature/Nomenclatures.service.ts
> +  return API.get(`/nomenclatures/counties`, { headers: { public: true } }).then((res) => res.data);
remove public:true

2022-08-11 08:30 UTC, birloiflorian approved these changes

2022-08-11 08:31 UTC, merged