fixes: NGO Open Data
code4romania/onghub pull request #57
Opened 2022-08-16 11:29 UTC by OlteanuCosmin

- C4R-418: limit input to 6 characters
- C4R-419: only positive numbers should be allowed
- C4R-420: missing error when decimal present
- C4R-424: redirected to wrong page
- C4R-425: missing error on invalid URL
- C4R-426: missing error on invalid file format

2022-08-17 12:27 UTC, radulescuandrew requested changes
@birloiflorian mai arunca o privire pe files te rog

2022-08-17 12:27 UTC, radulescuandrew commented on frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
> +    if (data.report?.startsWith('www')) {
Fix din Front-end. Addon-ul din frontend (Https) ar trebui sa puna valoare si sa trimita catre Backend, nu facem validarea aici

2022-08-17 12:27 UTC, radulescuandrew commented on frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
> +    if (!isExcel(file.name)) {
@birloiflorian readXlsxFile citeste si CSV-uri sau doar Excel?

Ar trebui sa avem un try/catch pe readXlsxFile sa parseze eroarea si sa afiseze eroarea

2022-08-17 13:49 UTC, radulescuandrew commented on frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
> +    if (data.report?.startsWith('www')) {
@dragos1195 uite-te tu te rog. Ar trebui sa fie concatenata valoarea `https://`

2022-08-22 09:27 UTC, dragos1195 commented on frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
> +    if (data.report?.startsWith('www')) {
https://wearetribus.atlassian.net/browse/C4R-466 Created a task for this. Should leave it like this for now so the testing will pass. Afterwards we'll change how the "http(s)" is appended.

2022-08-22 10:25 UTC, merged