C4R-74 View All apps (as Cards)
code4romania/onghub pull request #73
Opened 2022-08-31 12:22 UTC by dragos1195

C4R-74 

Added View Applications as Cards

All apps for the moment.

2022-09-01 08:53 UTC, dragos1195 commented
WIP

2022-09-11 18:47 UTC, radulescuandrew requested changes

2022-09-11 18:47 UTC, radulescuandrew commented on frontend/src/pages/requests/components/Request.tsx
> +  } = useOrganizationRequest(params.id ? params?.id : '');
Nu stiu daca "params" poate sa fie undefined, dar merita sa pui optional chaining si la "params.id" sau sa folosesti `id` destructurat pe linia 22.

2022-09-11 18:47 UTC, radulescuandrew commented on frontend/src/pages/requests/interfaces/OngApplication.interface.ts
> +  applicaiontId: number;
application*

2022-09-11 18:47 UTC, radulescuandrew commented on frontend/src/services/application/Application.queries.ts
> +export const useOngApplicationsQuery = () => {
Nu inteleg diferenta dintre `useOngApplicationsQuery` si `useMyOngApplicationsQuery` dpdv business logic. 

Ar trebui sa punem comments prin multe locuri in app.

2022-09-11 18:47 UTC, radulescuandrew commented on frontend/src/services/application/Application.service.ts
> +export const getOngApplications = async (): Promise<PaginatedEntity<ApplicationWithOngStatus>> => {
Nici /organization/application si /organization/application/profile nu inteleg

2022-09-11 18:47 UTC, radulescuandrew commented on frontend/src/services/request/Request.queries.ts
> +    ['applications/requests', limit, page, orderBy, orderDirection, search, interval],
Stringurile astea `applications/requests` apeleaza API-ul nu?

2022-09-12 08:31 UTC, dragos1195 commented on frontend/src/pages/application/Application.tsx
> +    navigate(-2);
https://wearetribus.atlassian.net/browse/C4R-616

2022-09-12 08:46 UTC, dragos1195 commented on frontend/src/services/request/Request.queries.ts
> +    ['applications/requests', limit, page, orderBy, orderDirection, search, interval],
Nu. Sunt query keys. 
React query administreaza cache-ul pe baza de query keys. 
Functia apelata este mai jos.

https://react-query-v2.tanstack.com/guides/query-keys#_top

2022-09-12 08:48 UTC, dragos1195 commented on frontend/src/pages/application/Application.tsx
>        deleteButton={{
Removed.

2022-09-12 08:48 UTC, dragos1195 commented on frontend/src/pages/apps-store/AllApplications.tsx
> +    const found: IPageTab | undefined = APPLICATION_STORE_TABS.find(
Added comment.

2022-09-12 08:49 UTC, dragos1195 commented on frontend/src/pages/apps-store/components/ApplicationListCards.tsx
> +const ApplicationListCards = ({ ong }: { ong?: boolean }) => {
Changed to isOngView. 

Pentru MyApps si AllApps as Admin sunt tot Cards. 
Am pus un parametru sa diferentiez ce call fac.

2022-09-12 08:50 UTC, dragos1195 commented on frontend/src/services/application/Application.queries.ts
> +export const useOngApplicationsQuery = () => {
Am adaugat comentarii la definitie

2022-09-12 08:50 UTC, dragos1195 commented on frontend/src/services/application/Application.service.ts
> +export const getOngApplications = async (): Promise<PaginatedEntity<ApplicationWithOngStatus>> => {
Adaugat comentarii

2022-09-12 10:47 UTC, merged