C4R-560 - Edit Organization Request
code4romania/onghub pull request #77
Opened 2022-09-09 08:54 UTC by dragos1195

C4R-560 - https://wearetribus.atlassian.net/browse/C4R-560

2022-09-13 14:57 UTC, birloiflorian requested changes

2022-09-13 14:57 UTC, birloiflorian commented on backend/src/modules/organization/entities/organization-request.entity.ts
> +  @Column({ type: 'varchar', name: 'organization_name', nullable: true })
Asta nu ar trebui sa fie nullable.

2022-09-13 14:57 UTC, birloiflorian commented on frontend/src/services/organization/Organization.service.ts
> +export const patchOrganizationById = (id: number, update: any): Promise<any> => {
Poti sa pui te rog in loc de any, tipul de data?

2022-09-14 09:00 UTC, dragos1195 commented on frontend/src/services/organization/Organization.service.ts
> +export const patchOrganizationById = (id: number, update: any): Promise<any> => {
O sa o sterg de tot, pentru ca folosim o metoda care exista deja.

2022-09-14 09:03 UTC, birloiflorian approved these changes

2022-09-14 09:04 UTC, merged