feat: [C4R-154] added dto validation
code4romania/onghub pull request #8
Opened 2022-06-28 13:34 UTC by OlteanuCosmin

- added dto validation for every dto so far
- switched from manual swagger decorators to swagger plugin to reduce boilerplate

2022-06-28 14:42 UTC, radulescuandrew requested changes

2022-06-28 14:42 UTC, radulescuandrew commented on backend/package.json
> +    "validator": "^13.7.0"
La ce e folosit asta?

2022-06-28 14:54 UTC, OlteanuCosmin commented on backend/package.json
> +    "validator": "^13.7.0"
Am vrut sa-l folosesc dar nu am mai avut nevoie, si am uitat sa-l dezinstalez inainte sa dau push.

2022-06-28 15:01 UTC, OlteanuCosmin commented on backend/src/modules/organization/dto/report.dto.ts
> +  @Max(2022)
Am modificat acum sa ia valoarea maxima current year.

2022-06-29 07:50 UTC, radulescuandrew approved these changes

2022-06-29 08:31 UTC, birloiflorian requested changes

2022-06-29 08:31 UTC, birloiflorian commented on backend/src/modules/organization/dto/create-contact.dto.ts
> +  @Matches(/^[a-zA-Z-]*$/)
FullName should support space and '-'.

2022-06-29 08:31 UTC, birloiflorian commented on backend/src/modules/organization/dto/create-contact.dto.ts
>    phone: string;
Phone should support only numeric characters

2022-06-29 08:31 UTC, birloiflorian commented on backend/src/modules/organization/dto/create-organization-activity.dto.ts
>    MaxLength,
Remove unused imports

2022-06-29 10:48 UTC, birloiflorian approved these changes

2022-06-30 07:44 UTC, merged