feat: added restrict organization API
code4romania/onghub pull request #89
Opened 2022-09-19 10:47 UTC by OlteanuCosmin

- C4R-653: create the API
- C4R-655: validate restriction

2022-09-20 08:22 UTC, birloiflorian requested changes

2022-09-20 08:22 UTC, birloiflorian commented on backend/src/modules/authentication/jwt.strategy.ts
> +    if (user.organization.status === OrganizationStatus.RESTRICTED) {
Aici nu cred ca ar trebui sa aruncam FrobiddenException ci UnauthorizedException ca mai sus, deoarece UserStatusGuard va arunca Forbidden

2022-09-20 08:22 UTC, birloiflorian commented on backend/src/modules/organization/organization.controller.ts
> +  @Patch(':id/restrict')
Lipsesc decoratorii de OpenApi

2022-09-20 14:01 UTC, OlteanuCosmin commented on backend/src/modules/authentication/jwt.strategy.ts
> +    if (user.organization.status === OrganizationStatus.RESTRICTED) {
Am schimbat.

2022-09-20 14:02 UTC, OlteanuCosmin commented on backend/src/modules/organization/organization.controller.ts
> +  @Patch(':id/restrict')
I-am pus.

2022-09-22 13:56 UTC, birloiflorian requested changes

2022-09-22 13:56 UTC, birloiflorian commented on backend/src/modules/authentication/jwt.strategy.ts
> +    if (user.organization.status === OrganizationStatus.RESTRICTED) {
Ai 2 if-uri consecutive care arunca aceiasi exceptie, ar trebui sa fie unul singur.

2022-09-22 14:05 UTC, OlteanuCosmin commented on backend/src/modules/authentication/jwt.strategy.ts
> +    if (user.organization.status === OrganizationStatus.RESTRICTED) {
Le-am combinat pe amandoua.

2022-09-23 14:00 UTC, birloiflorian approved these changes

2022-09-23 16:31 UTC, merged