feat: [C4R-679] API to create new reporting entries for last year
code4romania/onghub pull request #96
Opened 2022-09-22 10:50 UTC by radulescuandrew

Inserts 2 new entries in OrganizationFinancial Table (one for Expense and one for Income) for the currentYear - 1;

Inserts 1 new entry in Report table for currentYear

Inserts 1 new entry in Investor Table for currentYear

Inserts 1 new entry in Partner Table for currentYear

2022-09-23 09:08 UTC, birloiflorian requested changes

2022-09-23 09:08 UTC, birloiflorian commented on backend/src/modules/organization/services/organization.service.ts
> +    // console.log(organization.organizationReport.investors.length);
We should remove this.

2022-09-23 09:08 UTC, birloiflorian commented on backend/src/shared/services/anaf.service.ts
> +    console.log(`${ANAF_URL}?an=${year}&cui=${companyCUI}`);
We should remove this.

2022-09-26 11:40 UTC, radulescuandrew commented on backend/src/modules/organization/services/organization.service.ts
> +    // console.log(organization.organizationReport.investors.length);
Done.

2022-09-26 11:41 UTC, merged