feat: [C4R-118] Invited user list
code4romania/onghub pull request #99
Opened 2022-09-26 11:30 UTC by OlteanuCosmin

- C4R-268
- C4R-675
- C4R-676
- C4R-677

2022-09-26 17:01 UTC, radulescuandrew requested changes

2022-09-26 17:01 UTC, radulescuandrew commented on frontend/src/services/user/User.queries.ts
> +export const useCognitoUsersQuery = (search?: string, interval?: Date[]) => {
useInvitedUsers / usePendingUsers cum vrei tu dar sa fie consistent peste tot

2022-09-27 07:24 UTC, dragos1195 requested changes

2022-09-27 07:24 UTC, dragos1195 commented on backend/src/modules/user/services/user.service.ts
> +  ) {
add return type

2022-09-27 07:24 UTC, dragos1195 commented on backend/src/modules/user/admin-user.controller.ts
> +  @Get('cognito-users')
Endpoint-ul se numeste 'cognito-users' dar tu returnezi doar getInvitedUsers, care in interiorul metodei apeleaza GET pe cognito users care au statusul FORCE_CHANGE_PASSWORD. 

Nu e ok dpdv semantica numele endpoint-ului.

2022-09-27 07:57 UTC, OlteanuCosmin commented on backend/src/modules/user/admin-user.controller.ts
> +  @Get('cognito-users')
Am modificat.

2022-09-27 07:58 UTC, OlteanuCosmin commented on backend/src/modules/user/services/cognito.service.ts
> +    this.cognitoProvider.send(resendUserInvite);
Adaugat await.

2022-09-27 07:59 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
> +    // const invitedUsers: IInvites[] = [];
Scos.

2022-09-27 08:05 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
> +    this.cognitoService.resendInvite(user.email);
Adaugat tipul returnat si return.

2022-09-27 08:07 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
> +    data.map((item) => {
Modificat.

2022-09-27 08:09 UTC, OlteanuCosmin commented on backend/src/modules/user/admin-user.controller.ts
> +  @Get('cognito-users')
Redenumit in 'user/invitees'

2022-09-27 08:26 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
> +      emails.push(item.Attributes[3].Value);
Am modificat + adaugat tipul pentru 'item'.

2022-09-27 08:28 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
> +    if (search) {
Ce am folosit eu este o modificare pentru ce am avut eu nevoie la ce exista deja in base dao. Ea poate fi pusa in shared, dar nu stiu daca va mai fi folosita altundeva.

2022-09-27 08:39 UTC, OlteanuCosmin commented on frontend/src/assets/locales/ro/translation.json
> +    "updated_on": "Ultima actualizare",
In fisierele cu componente React ma folosesc de variabila 't' pentru a pune traducerile. Codul ar fi ceva de genul:
`const {t} = useTranlation(['user', 'common']);` unde 'user' este namescape-ul default iar tot ce este dupa este optional. 
`t('back', {ns: 'common'})`, unde in 'ns' se specifica namescape-ul din care se doreste traducerea cu cheia 'back'.

In fisierele care nu au componente React nu se poate folosi 't' si trebuie folosit un obiect creat de noi care retine traduceriile si constanta 'i18n' din config-ul pentru traduceri, de forma `name = i18n.t('user:account.name')` unde ce se afla inainte de ':' este numele ns-ului si dupa este cheia dorita.

2022-09-27 08:43 UTC, OlteanuCosmin commented on frontend/src/pages/users/components/UserInvites/UserInvites.tsx
> +    if (selectedInvite) setIsConfirmRemoveModalOpen(true);
Modificat in `selectedInviteeForDeletion` si `setSelectedInviteeForDeletion`.

2022-09-27 08:48 UTC, OlteanuCosmin commented on frontend/src/pages/users/components/UserInvites/UserInvites.tsx
> +      onSuccess: () => {
Este un `useEffect` care are linia `if (resendInviteMutation.error) useErrorToast(t('invites.resend_error'));`.

2022-09-27 08:49 UTC, OlteanuCosmin commented on frontend/src/services/user/User.queries.ts
> +export const useCognitoUsersQuery = (search?: string, interval?: Date[]) => {
Redenumit in `useInviteesQuery`.

2022-09-27 09:36 UTC, OlteanuCosmin commented on frontend/src/services/user/User.service.ts
> +  } else if (search) {
Modificat in doar 2 if-uri.

2022-09-27 18:14 UTC, radulescuandrew requested changes

2022-09-27 18:14 UTC, radulescuandrew commented on backend/src/modules/authentication/jwt.strategy.ts
> +    if (user?.organization?.status === OrganizationStatus.RESTRICTED) {
Si daca userul e restricted?

2022-09-27 18:14 UTC, radulescuandrew commented on backend/src/modules/user/services/user.service.ts
> +        if (obj.Name === 'email') return obj.Value;
```item.Attributes.find(attr => attr.Name === 'email')``` check array.find

2022-09-27 18:14 UTC, radulescuandrew commented on frontend/src/pages/users/components/UserInvites/UserInvites.tsx
> +      onSuccess: () => {
OK.

2022-09-28 07:42 UTC, OlteanuCosmin commented on backend/src/modules/authentication/jwt.strategy.ts
> +    if (user?.organization?.status === OrganizationStatus.RESTRICTED) {
Adaugat si verificarea pentru user restricted (nu facea parte din task though).

2022-09-28 07:43 UTC, OlteanuCosmin commented on backend/src/modules/user/services/user.service.ts
> +        if (obj.Name === 'email') return obj.Value;
Modificat.

2022-09-28 08:12 UTC, radulescuandrew commented on backend/src/modules/authentication/jwt.strategy.ts
>        throw new UnauthorizedException();
Cum facem diferenta in front-end intre cele 3 unauthorized exceptions? Facem erori specifice?

Odata trebuie sa afisam ecran cu organizatia restricted, odata cu userul restricted si odata un toast sau ceva cu eroarea cand nu gaseste userul.

2022-09-28 08:12 UTC, radulescuandrew commented on frontend/src/assets/locales/ro/translation.json
> +    "updated_on": "Ultima actualizare",
OK.

2022-09-29 08:04 UTC, OlteanuCosmin commented on backend/src/modules/authentication/jwt.strategy.ts
>        throw new UnauthorizedException();
O sa fie facut in PR-ul [https://github.com/code4romania/onghub/pull/100](url) pentru consistenta.

2022-09-29 08:16 UTC, radulescuandrew approved these changes

2022-09-29 08:17 UTC, merged